no.nav.security.oidc:
  issuers: intern
  issuer.intern:
    discoveryurl: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    accepted_audience: ${GYLDIGE_SRVBRUKERE}
    cookie_name: ID_token

SECURITYTOKENSERVICE_URL: https://sts.adeo.no/SecurityTokenServiceProvider/
STS_REST_URL: https://security-token-service.nais.adeo.no
AKTOERID_URL: https://app.adeo.no/aktoerregister/api/v1
PERSON_V3_URL: https://wasapp.adeo.no/tpsws/ws/Person/v3
MEDL2_URL: https://app.adeo.no/medl2/api/v1

# Appdynamics
APPDYNAMICS_CONTROLLER_HOST_NAME: appdynamics.adeo.no
APPDYNAMICS_CONTROLLER_PORT: 443
APPDYNAMICS_CONTROLLER_SSL_ENABLED: true
APPDYNAMICS_AGENT_ACCOUNT_NAME: PROD