no.nav.security.oidc:
  issuers: intern
  intern:
    discoveryurl: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    accepted_audience: ${ACCEPTEDAUDIENCE}
    cookie_name: ID_token