no.nav.security.oidc:
  issuers: intern
  issuer.intern:
    discoveryurl: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
    accepted_audience: ${GYLDIGE_SRVBRUKERE}
    cookie_name: ID_token

AAD_URL: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/v2.0/token
CLIENT_ID: ${CLIENT_ID}
CLIENT_SECRET: ${CLIENT_SECRET}
INFOTRYGD_KS_SCOPE: ${INFOTRYGD_KS_SCOPE}

SECURITYTOKENSERVICE_URL: https://sts.adeo.no/SecurityTokenServiceProvider/
AKTOERID_URL: https://app.adeo.no/aktoerregister
PERSON_V3_URL: https://wasapp.adeo.no/tpsws/ws/Person/v3
EGEN_ANSATT_V1_URL: https://wasapp.adeo.no/tpsws/EgenAnsatt_v1
DOKARKIV_V1_URL: https://dokarkiv.nais.adeo.no
MEDL2_URL: https://app.adeo.no/medl2
SAF_URL: http://saf
INNSYN_JOURNAL_V2_URL: https://wasapp.adeo.no/joark/InnsynJournal/v2

# Appdynamics
APPDYNAMICS_CONTROLLER_HOST_NAME: appdynamics.adeo.no
APPDYNAMICS_CONTROLLER_PORT: 443
APPDYNAMICS_CONTROLLER_SSL_ENABLED: true
APPDYNAMICS_AGENT_ACCOUNT_NAME: PROD